### ISSUE TITLE
.progress and .animateTo issue

### ISSUE THREAD

**Issue by AresProductions** [gregttn/GTProgressBar#24] opened 2018-05-19 15:15 UTC
I'm trying to show the animation every time the user opens the controller again. 

```
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        let percentage = CGFloat(completedBooksIsbn.count) / CGFloat(books.count)
        progressBar.progress = 0.0 // set progress to 0 to animate from there to percentage
        progressBar.animateTo(progress: percentage)
    }
```

The animation won't happen, the bar will stay where the first time animation stopped. 
I managed to find a solution by setting the `progressBar.progress = 0.0`  on `viewDidDisappear`

I just wanted to inform you in case you didn't know about this.

**Comment by gregttn** [comment] 2018-05-30 07:54
Thanks. Will have a look at this when I get a minute.

**Comment by gregttn** [comment] 2018-05-31 12:56
According to the documentation views should be configured in `viewWillAppear` and the any animations triggered in `viewDidAppear`. That means that your solution is correct.

The problem is that when you set the progress to be 0 the view requests to be updated by using `setNeedsLayout`. This will force the view to be redrawn on the next cycle. Then you are requesting the view to be animated. The animation starts but it is soon interrupted as the view's layout is ultimately invalidated. Finally the view is redrawn with the final progress value.

One solution I can think of is to force the view to update itself when the progress is updated instead od waiting for the next cycle.

**Comment by gregttn** [comment] 2018-05-31 18:04
I pushed a change to fix it. It will be released with the next version.

**Closed as completed by gregttn** 2018-05-31 18:04 UTC
Labels: bug
